language: node_js
node_js:
  - node
  - lts/*
sudo: false
before_install:
  - npm install -g npm@latest
  - npm install -g @adonisjs/cli
  - npm install
cache:
  npm: false
install:
  - adonis serve --dev